#+title: gherkin


https://cucumber.io/docs/gherkin/reference/
* example steps
You can have as many steps as you like, but we recommend 3-5 steps per example.
Having too many steps will cause the example to lose its expressive power as a
specification and documentation.
* given
When Cucumber executes a Given step, it will configure the system to be in a
well-defined state, such as creating and configuring objects or adding data to a
test database.

The purpose of Given steps is to put the system in a known state before the user
(or external system) starts interacting with the system (in the When steps).
Avoid talking about user interaction in Given’s. If you were creating use cases,
Given’s would be your preconditions.

* when
NOTE!
#+begin_quote
Most software does something people could do manually (just not as efficiently).

Try hard to come up with examples that don’t make any assumptions about
technology or user interface. Imagine it’s 1922, when there were no computers.

Implementation details should be hidden in the step definitions.
#+end_quote
* Background

Occasionally you’ll find yourself repeating the same Given steps in all of the
scenarios in a Feature.

Since it is repeated in every scenario, this is an indication that those steps
are not essential to describe the scenarios; they are incidental details. You
can literally move such Given steps to the background, by grouping them under a
Background section.

A Background allows you to add some context to the scenarios that follow it. It
can contain one or more Given steps, which are run before each scenario, but
after any Before hooks.

A Background is placed before the first Scenario/Example, at the same level of
indentation.

#+begin_comment
could we use this to set up a machine before our various scnarios?
#+end_comment
