#+title: gRPC


google Remote Procedure Call.  RPC is one of the two primary models of API design (the other being REST).  this is the google evolution of it.

It's aim is to allow for concise, typed, machine readable specifications for your API that works for http/2 and scales more easily than REST.

#+BEGIN_QUOTE
At it's core an api is a contract of "send me this request, and i will give you this response"
#+END_QUOTE
https://www.youtube.com/watch?v=XRXTsQwyZSU

gRPC is now a part of [[file:20210225154510-cncf.org][CNCF]]

remote procedure calls allow for client code that, when needing something from the server, looks like youare just calling a function /on/ the server.

* Uses [[file:20210225163355-protocol_buffers.org][protocol buffers]]
** Advantages
*** save network bandwidth
*** less cpu intensive so faster and more efficient communication
*** gRPC can be used by any language
*** easy to write message definitions
*** Definition separate from implementation, and much of implementation is generated by proto buffers
* API Oriented v. Resource oriented
it is af free design that lets youb uild an api based on the actual domain and
it's needs, and not just on the CRUD model (which is what [[file:20210217095055-rest.org][REST]] would use)
