#+title: flow

My current flow, a big todo of needs and such
* Inbox
* Projects
** Envoy Conformance
*** STRT Setup basic gameplan for rest of march
*** Meet with Riaan to discuss gameplan
*** Test Case written for xDS
**** Parse and understand the docs
** APISnoop low-maintenance
*** Webapp uses ineligible-endpoints.yaml to gather its endpoints
*** ineligible endpoints removed from database
*** releases on web app update near-automatically
*** releases on db update near-automatically
*** swagger.json created for 1.0 > 1.4
** NCW
*** DONE Attend Contribex Meeting
SCHEDULED: <2021-02-16 Tue 13:00>

*** DONE See practicality of adding tooltips
The intention is to be able to add definitions to an org file, these definitions then give a handy short summary of the term with maybe an additional link someone can follow.  This makes us able ot more concisely write our articles.

Initial pass would be to have a ~[def:]~  style link that includes word and longer definition all inline.  Second pass would be to reference a ~glossary.org~ within this repo where that word is defined and use that instead.  This is preferred, as we can define once and have multiple links to that definition.

I am going to work on the tufte.el file as it is the simplest written and I think I can add to it easy enough.
it is hard to do as a global package, but could be done as a file local variable i do think
*** DONE incorporate tooltip into ncw repo
*** TODO Write full, useful article for session 01
[[file:~/org/ncw/session-01.org][Session 01]]
*** TODO Style session 01 into a beautiful, easy to parse export
*** TODO capture changes needed in org file for this export
*** TODO export into reveal presentation
*** TODO Document changes needed to get working reveal presentation
*** TODO explore having both exports work from one file, else find alternative
** Kubecon Performance
*** STRT Watch the last con
*** Go through presentation with caleb
